name: Merge Auto

on:
  pull_request:
    types:
      - opened

jobs:

  auto-close:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Auto merge
        run: gh pr merge "$PR_NUMBER" --auto
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
